services:
  db:
    image: postgres:16
    container_name: konvent-pos-db
    environment:
      POSTGRES_USER: konvent
      POSTGRES_PASSWORD: konvent
      POSTGRES_DB: konvent_pos
    ports:
      - "5433:5432"
    volumes:
      - konvent_pos_data:/var/lib/postgresql/data

volumes:
  konvent_pos_data:
